### PR TITLE
Add code removed from bokeh 0.12.5 into InteractiveImage

### PR DESCRIPTION
**Pull request by StevenCHowell**
FWIW, this brings in the code removed from bokeh 0.12.5 which `InteractiveImage` relied on.  This serves to patch issue #293, though the discussion there 

> all of that recursive traversal to find a document somewhere was an ugly hack to work around a situation that no longer really occurs (at least not with any kind of normal usage). Dropping it in might "work" but it would not be my recommendation

motivates a closer review of the code that was brought over.

### CODE REVIEW

**Comment by philippjfr** [comment]
Thanks for fixing this @StevenCHowell. (Ab)using the context manager like this is something I originally did to avoid copying the code from bokeh. I think it can probably be factored out more cleanly now that we can't rely on bokeh for this anymore. I'll have a stab at it shortly as this is something I'll have to do for [holoviews](https://github.com/ioam/holoviews) anyway.

**Comment by philippjfr** [comment]
Thanks again for patching this so quickly. I think the solution used in https://github.com/bokeh/datashader/pull/296 will suffice because InteractiveImage is quite restricted in its usage anyway.

**Comment by philippjfr** [comment]
@StevenCHowell It seems this is required afterall, sorry for closing it earlier. I'll reopen this now, do you have time to rebase it? Otherwise I'd be happy to do so.

**Comment by StevenCHowell** [comment]
@philippjfr I just rebased my changes.  Hopefully the checks all pass and this is good to go.

**Comment by StevenCHowell** [comment]
I did not get a chance to check that the changes still fix the problem after doing the rebase.  If needed, I could test this tonight.

**Comment by philippjfr** [comment]
Did something go wrong with the rebase? The PR now includes various other, unrelated changes.

**Comment by StevenCHowell** [comment]
Maybe, first rebase.  I followed [this Git for Teams](http://gitforteams.com/resources/rebasing.html).  Basically, I updated the master branch of my fork from the datashader/master branch, then checked out this branch, and rebased in the changes from the master branch.

Perhaps I should simply close this PR, make a new branch, then copy over the changes there?

**Comment by jbednar** [comment]
That might be cleaner, thanks; this version looks like it will cause some issues...

**Comment by philippjfr** [comment]
That probably seems easiest, thanks again for doing this. Once you've done that I'm happy to test it still works.

**Pull request closed without merging**
