### PR TITLE
WIP: website

### PR DESCRIPTION
**Pull request by ceball**
Note: not ready for merging. Currently for testing nbsite as much as anything else...

Site as last built (manually) is at https://bokeh.github.io/datashader-docs/

To do:
* [x] Fill in placeholder content, making coherent
* [x] Fix notebook errors (see comment below)
* [ ] (CB) The API docs don't start out with anything useful; is that a datashader or an nbsite issue? https://bokeh.github.io/datashader-docs/api.html
* [ ] Make notebooks consistently have no title in first cell
* [ ] Name notebooks consistently, like `1_The_Title.ipynb` or `Another_Title.ipynb`, and update inter-notebook links to match.
* [ ] (CB) Make gallery (and/or restore deleted docs images to put on homepage?)

### CODE REVIEW

**Comment by ceball** [comment]
Below are the tracebacks I got in my terminal when running the notebooks. Note that this may just be from failing to set up datashader properly, and thus won't happen to others.

```
reading sources... [ 56%] topics/network_packets
INFO: Running temp notebook /Users/cball/code/bokeh/datashader/docs/_build/html/topics/network_packets_temp_evaluated.ipynb
Executing notebook with kernel: python3

An error occurred while executing the following cell:
------------------
%%opts RGB [width=800 height=800] Nodes (size=8)
target_counts = list(edges_df.groupby('target').count().sort_values('weight').iloc[-20:].index.values)
(datashade(forceatlas, cmap=datashade.cmap[128:]) * datashade(forceatlas.nodes, cmap=['cyan']) *
 forceatlas.nodes.select(index=target_counts))
------------------

--------------------------------------------------------------------
TypeError                          Traceback (most recent call last)
<ipython-input-9-37f1af05aede> in <module>()
      1 target_counts = list(edges_df.groupby('target').count().sort_values('weight').iloc[-20:].index.values)
----> 2 (datashade(forceatlas, cmap=datashade.cmap[128:]) * datashade(forceatlas.nodes, cmap=['cyan']) *
      3  forceatlas.nodes.select(index=target_counts))

TypeError: 'NoneType' object is not subscriptable
TypeError: 'NoneType' object is not subscriptable
```

```
reading sources... [ 63%] topics/opensky
INFO: Running temp notebook /Users/cball/code/bokeh/datashader/docs/_build/html/topics/opensky_temp_evaluated.ipynb
Executing notebook with kernel: python3

An error occurred while executing the following cell:
------------------
%%time
import pandas as pd

flightpaths = pd.read_hdf('../data/opensky.h5', 'flights')
flightpaths['origin']    = flightpaths.origin.astype('category')
flightpaths['on_ground'] = flightpaths.on_ground.astype('category')
flightpaths['ascending'] = flightpaths.ascending.astype('category')
------------------

--------------------------------------------------------------------
FileNotFoundError                  Traceback (most recent call last)
<timed exec> in <module>()

~/Eunectes/mc3/envs/dsdev/lib/python3.6/site-packages/pandas/io/pytables.py in read_hdf(path_or_buf, key, mode, **kwargs)
    345         if not exists:
    346             raise compat.FileNotFoundError(
--> 347                 'File %s does not exist' % path_or_buf)
    348 
    349         store = HDFStore(path_or_buf, mode=mode, **kwargs)

FileNotFoundError: File ../data/opensky.h5 does not exist
FileNotFoundError: File ../data/opensky.h5 does not exist
```

```
reading sources... [ 66%] topics/osm
INFO: Running temp notebook /Users/cball/code/bokeh/datashader/docs/_build/html/topics/osm_temp_evaluated.ipynb
Executing notebook with kernel: python3

An error occurred while executing the following cell:
------------------
diag.visualize([prof, rprof])
None
------------------

--------------------------------------------------------------------
ImportError                        Traceback (most recent call last)
<ipython-input-6-bd1b5353d3da> in <module>()
----> 1 diag.visualize([prof, rprof])
      2 None

~/Eunectes/mc3/envs/dsdev/lib/python3.6/site-packages/dask/diagnostics/profile_visualize.py in visualize(profilers, file_path, show, save, **kwargs)
    169     """
    170     bp = import_required('bokeh.plotting', _BOKEH_MISSING_MSG)
--> 171     from bokeh.io import _state
    172 
    173     if not _state._notebook:

ImportError: cannot import name '_state'
ImportError: cannot import name '_state'
```

```
reading sources... [ 76%] topics/solar
INFO: Running temp notebook /Users/cball/code/bokeh/datashader/docs/_build/html/topics/solar_temp_evaluated.ipynb
Executing notebook with kernel: python3

An error occurred while executing the following cell:
------------------
usaf_data = read_one_station(example_usaf)
hour_of_day = plot_gen(grouper='hour', usaf_data=usaf_data)
------------------

--------------------------------------------------------------------
KeyError                           Traceback (most recent call last)
~/Eunectes/mc3/envs/dsdev/lib/python3.6/site-packages/pandas/core/indexes/base.py in get_loc(self, key, method, tolerance)
   2521             try:
-> 2522                 return self._engine.get_loc(key)
   2523             except KeyError:

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: 'metstat_glo_wh_m_2_low'

During handling of the above exception, another exception occurred:

KeyError                           Traceback (most recent call last)
<ipython-input-21-91ba89bb9cd3> in <module>()
      1 usaf_data = read_one_station(example_usaf)
----> 2 hour_of_day = plot_gen(grouper='hour', usaf_data=usaf_data)

<ipython-input-16-cff2bbcfdb64> in plot_gen(station, grouper, usaf_data)
     20                                  periods=summary_df.shape[0])
     21         median_col = summary_df[col]
---> 22         low_col = summary_df[col + '_low']
     23         hi_col = summary_df[col + '_hi']
     24         hi = hv.Curve((dates, hi_col), label=label + ' (upper quartile)')(**kw)

~/Eunectes/mc3/envs/dsdev/lib/python3.6/site-packages/pandas/core/frame.py in __getitem__(self, key)
   2137             return self._getitem_multilevel(key)
   2138         else:
-> 2139             return self._getitem_column(key)
   2140 
   2141     def _getitem_column(self, key):

~/Eunectes/mc3/envs/dsdev/lib/python3.6/site-packages/pandas/core/frame.py in _getitem_column(self, key)
   2144         # get column
   2145         if self.columns.is_unique:
-> 2146             return self._get_item_cache(key)
   2147 
   2148         # duplicate columns & possible reduce dimensionality

~/Eunectes/mc3/envs/dsdev/lib/python3.6/site-packages/pandas/core/generic.py in _get_item_cache(self, item)
   1840         res = cache.get(item)
   1841         if res is None:
-> 1842             values = self._data.get(item)
   1843             res = self._box_item_values(item, values)
   1844             cache[item] = res

~/Eunectes/mc3/envs/dsdev/lib/python3.6/site-packages/pandas/core/internals.py in get(self, item, fastpath)
   3836 
   3837             if not isna(item):
-> 3838                 loc = self.items.get_loc(item)
   3839             else:
   3840                 indexer = np.arange(len(self.items))[isna(self.items)]

~/Eunectes/mc3/envs/dsdev/lib/python3.6/site-packages/pandas/core/indexes/base.py in get_loc(self, key, method, tolerance)
   2522                 return self._engine.get_loc(key)
   2523             except KeyError:
-> 2524                 return self._engine.get_loc(self._maybe_cast_indexer(key))
   2525 
   2526         indexer = self.get_indexer([key], method=method, tolerance=tolerance)

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: 'metstat_glo_wh_m_2_low'
KeyError: 'metstat_glo_wh_m_2_low'
```

```
reading sources... [ 90%] user_guide/Plotting_pitfalls
INFO: Running temp notebook /Users/cball/code/bokeh/datashader/docs/_build/html/user_guide/1-Plotting_pitfalls_temp_evaluated.ipynb
Executing notebook with kernel: python3

An error occurred while executing the following cell:
------------------
hmap = hv.HoloMap({0:blues,0.000001:reds,1:blues,2:reds}, key_dimensions=['level'])
hv.Scatter3D(hmap.table(), kdims=['x','y','level'], vdims=['c'])
------------------

--------------------------------------------------------------------
DataError                          Traceback (most recent call last)
<ipython-input-3-d3643992729e> in <module>()
      1 hmap = hv.HoloMap({0:blues,0.000001:reds,1:blues,2:reds}, key_dimensions=['level'])
----> 2 hv.Scatter3D(hmap.table(), kdims=['x','y','level'], vdims=['c'])

~/code/ioam/holoviews3/holoviews/core/data/__init__.py in __init__(self, data, kdims, vdims, **kwargs)
    192         validate_vdims = kwargs.pop('_validate_vdims', True)
    193         super(Dataset, self).__init__(data, **dict(kwargs, **dict(dims, **extra_kws)))
--> 194         self.interface.validate(self, validate_vdims)
    195 
    196         self.redim = redim(self, mode='dataset')

~/code/ioam/holoviews3/holoviews/core/data/pandas.py in validate(cls, dataset, vdims)
    115             raise DataError("Supplied data does not contain specified "
    116                             "dimensions, the following dimensions were "
--> 117                             "not found: %s" % repr(not_found), cls)
    118 
    119 

DataError: Supplied data does not contain specified dimensions, the following dimensions were not found: ['level']

PandasInterface expects tabular data, for more information on supported datatypes see http://holoviews.org/user_guide/Tabular_Datasets.html
DataError: Supplied data does not contain specified dimensions, the following dimensions were not found: ['level']

PandasInterface expects tabular data, for more information on supported datatypes see http://holoviews.org/user_guide/Tabular_Datasets.html
```

```
reading sources... [ 93%] user_guide/Timeseries
INFO: Running temp notebook /Users/cball/code/bokeh/datashader/docs/_build/html/user_guide/3-Timeseries_temp_evaluated.ipynb
Executing notebook with kernel: python3

An error occurred while executing the following cell:
------------------
from datashader.bokeh_ext import InteractiveImage
def create_image(x_range, y_range, w, h):
    cvs = ds.Canvas(x_range=x_range, y_range=y_range,
                    plot_height=h, plot_width=w)
    aggs = OrderedDict((c,cvs.line(df, 'Time', c, agg=ds.count())) for c in cols)
    renamed = [aggs[key].rename({key: 'value'}) for key in aggs]
    merged = xr.concat(renamed, 'cols')
    total = merged.sum(dim='cols')
    img = tf.shade(total, how='linear')
    return img
    
p = base_plot()
InteractiveImage(p, create_image)
------------------

--------------------------------------------------------------------
ValueError                         Traceback (most recent call last)
<ipython-input-13-b5522a864409> in <module>()
     10     return img
     11 
---> 12 p = base_plot()
     13 InteractiveImage(p, create_image)

<ipython-input-12-b92f912bdd42> in base_plot(tools)
     14         x_range=x_range, y_range=y_range, outline_line_color=None,
     15         min_border=0, min_border_left=0, min_border_right=0,
---> 16         min_border_top=0, min_border_bottom=0, responsive=True)   
     17     p.xgrid.grid_line_color = None
     18     p.ygrid.grid_line_color = None

~/Eunectes/mc3/envs/dsdev/lib/python3.6/site-packages/bokeh/plotting/figure.py in figure(**kwargs)
    775     '''
    776 
--> 777     return Figure(**kwargs)
    778 
    779 

~/Eunectes/mc3/envs/dsdev/lib/python3.6/site-packages/bokeh/plotting/figure.py in __init__(self, *arg, **kw)
    147         _process_axis_and_grid(self, opts.y_axis_type, opts.y_axis_location, opts.y_minor_ticks, opts.y_axis_label, self.y_range, 1)
    148 
--> 149         tool_objs, tool_map = _process_tools_arg(self, opts.tools)
    150         self.add_tools(*tool_objs)
    151         _process_active_tools(self.toolbar, tool_map, opts.active_drag, opts.active_inspect, opts.active_scroll, opts.active_tap)

~/Eunectes/mc3/envs/dsdev/lib/python3.6/site-packages/bokeh/plotting/helpers.py in _process_tools_arg(plot, tools)
    523             continue
    524 
--> 525         tool_obj = _tool_from_string(tool)
    526         tool_objs.append(tool_obj)
    527         tool_map[tool] = tool_obj

~/Eunectes/mc3/envs/dsdev/lib/python3.6/site-packages/bokeh/plotting/helpers.py in _tool_from_string(name)
    460             matches, text = known_tools, "possible"
    461 
--> 462         raise ValueError("unexpected tool name '%s', %s tools are %s" % (name, text, nice_join(matches)))
    463 
    464 

ValueError: unexpected tool name 'resize', similar tools are reset
ValueError: unexpected tool name 'resize', similar tools are reset
```

**Comment by jbednar** [comment]
I don't get any tracebacks in my notebooks now, locally, though I did have to install libgdal from conda-forge to get landsat to work.  May now be fixed on the main channel.

**Comment by jbednar** [comment]
Can we merge this and open a new issue for remaining errata?

**Comment by ceball** [comment]
@jbednar, if you merge I'll file the following issues (feel free to add/update the list):

* [ ] Homepage 'other resources' looks ugly (either align with previous block, or have previous block expand sooner after the twitter feed
* [ ] Add a gallery (and/or restore deleted docs images to put on homepage?)
* [ ] Create a datashader style (color scheme, etc)
* [ ] The API docs don't start out with anything useful; is that a datashader or an nbsite issue? https://bokeh.github.io/datashader-docs/api.html

**Comment by ceball** [comment]
(Opened #542 to cover the above)

**Pull request merged**
