### PR TITLE
Change link to docs

### PR DESCRIPTION
**Pull request by clemens-tolboom**
I changed the link in the _Learning more_ section but what should we do with the Documentation Status?

```
[![Documentation Status](https://readthedocs.org/projects/datashader/badge/?version=latest)](http://datashader.readthedocs.org/en/latest/?badge=latest)
```

### CODE REVIEW

**Comment by jbednar** [comment]
Thanks!  The docs outgrew what readthedocs could handle, and they are now built in a manual step, so there's no meaningful doc status.  So I guess that badge should also be removed.

**Comment by clemens-tolboom** [comment]
There is still __readthedocs.yml__ file. Is that used for manual building? Reading the `docs/README.md` I guess not. So will push that too.

**Comment by jbednar** [comment]
Thanks for handling all our loose ends! :-)

**Comment by clemens-tolboom** [comment]
I like the images :-p

**Comment by jbednar** [comment]
Thanks for the contribution!

**Pull request merged**
