### PR TITLE
Add edge ID to bundled dataframe

### PR DESCRIPTION
**Pull request by jbcrail**
The edge ID is added to the bundled dataframe so that a user can retrieve the additional edge metadata without copying it into the dataframe.

The implementation was refactored for two reasons:

1. The edge segment constants and methods are collected into a specialized class. This replaces using the dimensions of an edge to differentiate.

2. We can now switch to structured NumPy arrays or XArray for easier reference to the individual points (instead of opaque numeric indices).

### CODE REVIEW

**Comment by philippjfr** [comment]
Looks good to me, one question I have is whether there is an option to control whether to include the index or not to avoid the additional memory overhead if you don't need it. Doesn't seem like a major issue though, just want to be clear.

**Comment by jbcrail** [comment]
Thanks! The index and edge ids are mandatory at this time, but both can be made optional. It should be easier now to toggle edge ids as needed.

**Comment by jbednar** [comment]
Ok, please make them optional and we can then merge this.

**Comment by jbcrail** [comment]
@philippjfr I've made the edge IDs optional by default in the bundled dataframe.

Regarding the index, I'm unclear as to which index to make optional. Are you referring to the index on the provided edge dataframe?

**Comment by philippjfr** [comment]
I really only meant the edge ids, sorry for the confusion in terminology above.

**Comment by jbcrail** [comment]
No problem. Thanks for clearing this up.

**Comment by jbednar** [comment]
Ok, looks like it's ready to merge.

**Pull request merged**
