### PR TITLE
InteractiveImage callback checks if underscore is available

### PR DESCRIPTION
**Pull request by philippjfr**
Small fix to ensure zooming does not break on static pages.

### CODE REVIEW

**Comment by jbednar** [comment]
Thanks!

**Comment by jbednar** [comment]
Unfortunately, I don't see any change in the results, zooming still goes horizontally even after regenerating: https://anaconda.org/jbednar/uber/notebook

**Comment by philippjfr** [comment]
Doesn't look like you've updated, I still see this in the output:

```
        var throttled_cb = Bokeh._throttle['d29af1a4_8064_4f35_a94e_86862076eab2'];
        if (throttled_cb) {
            throttled_cb()
        } else {
            Bokeh._throttle['d29af1a4_8064_4f35_a94e_86862076eab2'] = _.throttle(update_plot, 500,
                                                  {leading: false});
            Bokeh._throttle['d29af1a4_8064_4f35_a94e_86862076eab2']()
        }
```

**Comment by jbednar** [comment]
Ah; I'd updated, but InteractiveImage has recently moved from callbacks.py to bokeh_ext.py. This notebook was still importing from callbacks and (unfortunately) finding it in an old stray callbacks.pyc file.  Damned .pyc files! Still no effect that I can see, though: https://anaconda.org/jbednar/uber/notebook

**Comment by philippjfr** [comment]
You're right, it was still broken. Sorry about that, it obviously can't work but something was masking the bug for me. Pushed a fix and reopening shortly.

**Pull request merged**
