### PR TITLE
Tweaks for NYC taxi example and update call to pipeline

### PR DESCRIPTION
**Pull request by birdsarah**

### CODE REVIEW

**Comment by birdsarah** [comment]
Maybe this should have been two PRs.

The second commit fixes what appears to be a small bug in datashader.

The first commit is just some small bokeh clean-ups based on my experience running through the example for the first time.

**Comment by jcrist** [comment]
Oh, yeah, that bug was my fault. I didn't expect changing the name of a positional arg to break anything, but that's why we have tests :/. Still need to get tests in for this (perhaps @philippjfr, if you'd be interested :)). Thanks for the fix!

**Comment by philippjfr** [comment]
@jcrist Sure, I'll try to put some together tomorrow.

**Comment by jcrist** [comment]
@birdsarah, this looks good to me. Is this good to merge?

**Comment by jbednar** [comment]
Thanks for those updates!  I'd be happy to have it merged, but what did you mean by "the black line makes it a bit of a false comparison on the initial plots"?

**Comment by jbednar** [comment]
@jcrist, those positional args used to be keyword args, when trying to decide on a clean interface.  I think it's good now, with these fixes.

**Comment by jcrist** [comment]
This looks fine to me, and would be nice to get in before tagging a release. Merging.

**Pull request merged**
