### PR TITLE
Datashader Notebook Example

### PR DESCRIPTION
**Pull request by brendancol**
- [x] integrate `ImageRGBA`
- [x] update with notebook kernal callbacks
- [x] fix `dh=[ymax - ymin]` issue

### CODE REVIEW

**Comment by jbednar** [comment]
Looks good.  I'm eager to see the packaged-up version, with the JS tucked away inside a class to leave what the user actually does need to mess with.  Looking at the code for create_image and relating that to the Bokeh code above, it looks like there is lots of stuff to do with x and y ranges.  Since create_image is something that we know is going to be called by Bokeh, can we put some bokeh-specific code that will get the ranges out of the Bokeh plot (instead of explicitly putting in p.height, etc. inside create_image)?  It Seems like there ought to be a way to simplify that...

**Comment by jcrist** [comment]
Is there a way to not embed bokehjs in the notebook, but instead have it pull from a cdn? This notebook is 78,000 over lines long!

**Comment by jcrist** [comment]
```python
from bokeh.io import output_notebook
from bokeh.resources import CDN
output_notebook(CDN)
```

Could you add this, rerun the notebook, and squash out the previous commits? Trying to keep down repo bloat from large blobs. Not a super big deal, just a preference.

**Comment by jbednar** [comment]
Changing it to use CDN by default sounds reasonable, but my personal preference is just not to commit any notebooks that have not been cleared, so that diffs work across github versions.  So I'd vote for clearing, committing, and *then* squashing previous commits.

**Comment by brendancol** [comment]
I've add the notebook example.  The goal of the notebook is to tell the story of datashader starting with showing the problem of over-saturation when plotting too many points:

A few points...
screen shot 2016-01-28 at 9 55 50 pm

Too many points..
screen shot 2016-01-28 at 9 56 00 pm


Datashader to the rescue...
screen shot 2016-01-28 at 9 56 12 pm

**Comment by jbednar** [comment]
Cool, thanks!  I'll merge when it's on a new PR; should be easy to make one since it's just one, new file.  Or else just add the new file directly, with no PR.

**Comment by brendancol** [comment]
merged...

**Pull request closed without merging**
